/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FutureRouteImport } from './routes/future'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecognitionRouteImport } from './routes/recognition'
import { Route as ProgrammesEducationRouteImport } from './routes/programmes/education'
import { Route as ProgrammesLivelihoodSkillsRouteImport } from './routes/programmes/livelihood-skills'
import { Route as ProgrammesWomenEmpowermentRouteImport } from './routes/programmes/women-empowerment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecognitionRoute = RecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesEducationRoute = ProgrammesEducationRouteImport.update({
  id: '/programmes/education',
  path: '/programmes/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesLivelihoodSkillsRoute =
  ProgrammesLivelihoodSkillsRouteImport.update({
    id: '/programmes/livelihood-skills',
    path: '/programmes/livelihood-skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesWomenEmpowermentRoute =
  ProgrammesWomenEmpowermentRouteImport.update({
    id: '/programmes/women-empowerment',
    path: '/programmes/women-empowerment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/future': typeof FutureRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/recognition': typeof RecognitionRoute
  '/programmes/education': typeof ProgrammesEducationRoute
  '/programmes/livelihood-skills': typeof ProgrammesLivelihoodSkillsRoute
  '/programmes/women-empowerment': typeof ProgrammesWomenEmpowermentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/future': typeof FutureRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/recognition': typeof RecognitionRoute
  '/programmes/education': typeof ProgrammesEducationRoute
  '/programmes/livelihood-skills': typeof ProgrammesLivelihoodSkillsRoute
  '/programmes/women-empowerment': typeof ProgrammesWomenEmpowermentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/future': typeof FutureRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/leadership': typeof LeadershipRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/recognition': typeof RecognitionRoute
  '/programmes/education': typeof ProgrammesEducationRoute
  '/programmes/livelihood-skills': typeof ProgrammesLivelihoodSkillsRoute
  '/programmes/women-empowerment': typeof ProgrammesWomenEmpowermentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/donate'
    | '/future'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/recognition'
    | '/programmes/education'
    | '/programmes/livelihood-skills'
    | '/programmes/women-empowerment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/donate'
    | '/future'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/recognition'
    | '/programmes/education'
    | '/programmes/livelihood-skills'
    | '/programmes/women-empowerment'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/donate'
    | '/future'
    | '/get-involved'
    | '/impact'
    | '/leadership'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/recognition'
    | '/programmes/education'
    | '/programmes/livelihood-skills'
    | '/programmes/women-empowerment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  FutureRoute: typeof FutureRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  LeadershipRoute: typeof LeadershipRoute
  PartnersRoute: typeof PartnersRoute
  ProgramsRoute: typeof ProgramsRoute
  ProjectsRoute: typeof ProjectsRoute
  RecognitionRoute: typeof RecognitionRoute
  ProgrammesEducationRoute: typeof ProgrammesEducationRoute
  ProgrammesLivelihoodSkillsRoute: typeof ProgrammesLivelihoodSkillsRoute
  ProgrammesWomenEmpowermentRoute: typeof ProgrammesWomenEmpowermentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recognition': {
      id: '/recognition'
      path: '/recognition'
      fullPath: '/recognition'
      preLoaderRoute: typeof RecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/education': {
      id: '/programmes/education'
      path: '/programmes/education'
      fullPath: '/programmes/education'
      preLoaderRoute: typeof ProgrammesEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/livelihood-skills': {
      id: '/programmes/livelihood-skills'
      path: '/programmes/livelihood-skills'
      fullPath: '/programmes/livelihood-skills'
      preLoaderRoute: typeof ProgrammesLivelihoodSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/women-empowerment': {
      id: '/programmes/women-empowerment'
      path: '/programmes/women-empowerment'
      fullPath: '/programmes/women-empowerment'
      preLoaderRoute: typeof ProgrammesWomenEmpowermentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  FutureRoute: FutureRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  LeadershipRoute: LeadershipRoute,
  PartnersRoute: PartnersRoute,
  ProgramsRoute: ProgramsRoute,
  ProjectsRoute: ProjectsRoute,
  RecognitionRoute: RecognitionRoute,
  ProgrammesEducationRoute: ProgrammesEducationRoute,
  ProgrammesLivelihoodSkillsRoute: ProgrammesLivelihoodSkillsRoute,
  ProgrammesWomenEmpowermentRoute: ProgrammesWomenEmpowermentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
